### PR TITLE
Fix #381: add ZIOSparkApp

### LINKED ISSUE #381: When running in Yarn, successful jobs using ZIOApp are marked as failed
`ZIOApp` calls `System.exit` on completion (see [here](https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/ZIOApp.scala#L74)), which will cause Yarn to fail the job with the error "Shutdown hook called before final status was reported" (even though the pipeline actually completes successfully). Further explanation of this behavior can be found [here](https://stackoverflow.com/questions/39580449/spark-jobs-running-on-emr-cluster-system-exit0-used-to-gracefully-completion). I believe we need to create our own `ZIOSparkApp` that doesn't call `System.exit` on completion.

### PR DESCRIPTION
**Pull request by nrmilstein**
Here is the `ZIOSparkApp` (and `ZIOSparkAppDefault`) I've been using. I also changed the examples to extend it – I'm not sure if that's necessary. I didn't know where exactly to add it in the code, so I've put it in "experimental" for now.

I'm not sure if the `interruptRootFibers` function is necessary, but I have left it in from ZIO's `ZIOApp`.

ZIO'S `ZIOApp` also handles catastrophic failures [here](https://github.com/zio/zio/blob/series/2.x/core/jvm/src/main/scala/zio/ZIOAppPlatformSpecific.scala#L39C21-L39C21), but I couldn't access those functions as they are private.

I can't really think of a way to test this class. A test to ensure it works with Yarn would make sure the `System.exit` function is never called. I suppose I could write a test that calls `ZIOSparkApp.main` and ensures the system hasn't exited (by simply continuing...); otherwise I'm not sure.

### CODE REVIEW

File: zio-spark-core/src/main/scala/zio/spark/experimental/ZIOSparkAppDefault.scala [hunk 1]
```diff
@@ -0,0 +1,9 @@
+package zio.spark.experimental
+
+import zio._
+
+trait ZIOSparkAppDefault extends ZIOSparkApp {
+  type Environment = Any
+
+  val bootstrap: ZLayer[ZIOAppArgs, Any, Any] = ZLayer.empty
```
Comment (ahoy-jon) [inline zio-spark-core/src/main/scala/zio/spark/experimental/ZIOSparkAppDefault.scala:8]: maybe, we should get the `sparkSession` from config directly. So the `ZIOSparkAppDefault` can be used directly.

Comment (nrmilstein) [reply zio-spark-core/src/main/scala/zio/spark/experimental/ZIOSparkAppDefault.scala:8]: That might be good. In my app, I don't want to start the SparkSession on launch, because there are some commands (like `--help`) that don't need it. Perhaps that would be cause for another trait, e.g. `ZIOSparkSessionConfig`
